personal_website/app.py
import datetime
import os

from flask import Flask  # pip install Flask
from flask import render_template
from flask import send_from_directory
from flask import request

from apps.portfolio.views import portfolio
from apps.utilities.files import read_from_file


app = Flask(__name__)
app.register_blueprint(portfolio, url_prefix='/')


@app.route('/media/<path:filename>')
def media(filename):
	return send_from_directory(f'{os.path.dirname(os.path.abspath(__file__))}/media', filename, as_attachment=True)


@app.errorhandler(404)
def page_not_found(e):
	try:
		content = read_from_file('content/content.json')
		page_info = content['pages']['404']
		mascot = read_from_file('content/mascot.txt')
		year = datetime.date.today().strftime("%Y")
		return render_template('error.html', page_info=page_info, tagline="Error 404", content=content, mascot=mascot, year=year), 404
	except KeyError:
		return r'<h1>404 Page not found :(</h1><a href="/">Home</a>'


@app.context_processor
def inject_now():
	"""Injects variables to all templates.
	
	Decorators:
		app.context_processor
	"""
	return {'year': datetime.date.today().strftime("%Y")}


@app.route('/robots.txt')
def get_static_file_from_root():
    return send_from_directory(app.static_folder, request.path[1:])

personal_website/apps/portfolio/views.py
from apps.utilities.files import read_from_file, get_content_json
from flask import Blueprint
from flask import render_template
from flask import abort

portfolio = Blueprint('portfolio', __name__, template_folder='portfolio/',
                      static_folder='static', static_url_path='/static')


@portfolio.route('/')
def homepage():
    page_info, content = get_content_json('portfolio')

    about_text = read_from_file('content/about.txt')
    mascot = read_from_file('content/mascot.txt')

    projects = read_from_file('content/projects.json', 'projects')

    return render_template(f'{portfolio.template_folder}homepage.html', page_info=page_info, projects=projects, about_text=about_text, content=content, mascot=mascot)


@portfolio.route('/info')
def info():
    page_info, content = get_content_json('info')

    privacy_text = read_from_file('content/privacy.txt')
    accessibility_text = read_from_file('content/accessibility.txt')

    return render_template(f'{portfolio.template_folder}info.html', page_info=page_info, content=content, privacy_text=privacy_text, accessibility_text=accessibility_text)

personal_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		{% include 'modules/meta.html' %}
		{% block styles %}
			<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/optimized.css')}}" media="screen" />
			<style>
				@font-face {
					font-family: "Raleway";
					src: local("Raleway-ExtraLight"), url("{{url_for('static', filename='fonts/third_party/Raleway-ExtraLight.ttf')}}");
					font-display: swap;
				}
				@font-face {
					font-family: "Inconsolata";
					src: local("Inconsolata-ExtraLight"), url("{{url_for('static', filename='fonts/third_party/Inconsolata-ExtraLight.ttf')}}");
					font-display: swap;
				}
			</style>
		{% endblock %}
	</head>
	<body>
		{% block header %}
			{% include 'modules/header.html' %}
		{% endblock %}
		<main>
			{% block content %}
			{% endblock %}
		</main>
		{% include 'modules/footer.html' %}
	</body>
</html>

personal_website/templates/error.html
{% extends "./base.html" %}
{% block content %}
<section class="section">
	<h2 class="section__headline">{{ page_info.tagline }}</h2>
	<p class="section__text">{{ page_info.description }}</p>
	{% with text = 'Sorry, something went wrong' %}
	{% include 'modules/mascot.html' %}
	{% endwith %}
	<nav aria-label="Links that take you back to other parts of this website">
		{% for link in page_info.links %}
		<a class="button" href="{{ link.url }}">{{ link.label }}</a>
		{% endfor %}
	</nav>
</section>
{% endblock %}

personal_website/templates/modules/about.html
<section class="section" id="about">
	<h2 class="section__headline">About Me</h2>
	{% if about_text %}
	<p class="section__text">{{ about_text }}</p>
	{% endif %}
	{% with text = 'Welcome' %}
	{% include 'modules/mascot.html' %}
	{% endwith %}
	<nav aria-label="My profiles on other websites">
		{% for link in content.quick_links %}
		<a class="button" href="{{ link.url }}">{{ link.label }}</a>
		{% endfor %}
	</nav>
</section>

personal_website/templates/modules/featured_projects.html
{% if projects %}
<section class="section" id="projects">
	<h2 class="section__headline">Featured Projects</h2>
	<a class="button" href="#about">About me</a>
	<div class="desktop-card-grid">
		{% for project in projects %}
		<div class="project">
			<picture class="project__thumbnail">
				{% for type in project.thumbnail.types[1:] %}
   				<source srcset="{{ url_for('media', filename=project.thumbnail.name + '.' + type) }}" type="image/{{ type }}">
   				{% endfor %}
   				<img loading="lazy" src="{{ url_for('media', filename=project.thumbnail.name + '.' + project.thumbnail.types[0]) }}" width="854" height="480" alt="{{ project.thumbnail.alt }}">
			</picture>
			<h3 class="project__title">{{ project.title }} ({{ project.date }})</h3>
			<p class="project__description">{{ project.description }}</p>
			<ul class="project__list">
				{% for link in project.links %}
				<li class="project__list-item"><a class="project__link" href="{{ link.url }}">{{ link.label }}</a></li>
				{% endfor %}
			</ul>
		</div>
		{% endfor %}
	</div>
</section>
{% endif %}

personal_website/templates/modules/footer.html
<footer class="footer">
	<div class="container">
		<p class="footer__cp">
			Made with passion by {{ content.name }} {% if content.nick %}({{ content.nick }}){% endif %}<br><br>
			&copy; {{ year }} {{ content.name }}
		</p>
		<nav aria-label="Footer links to more resources about this website">
			<ul class="footer__list">
				<li class="footer__list-item"><a class="footer__link" href="/">Home</a></li>
				<li class="footer__list-item"><a class="footer__link" href="{{ url_for('portfolio.info') }}#privacy">Privacy</a></li>
				<li class="footer__list-item"><a class="footer__link" href="{{ url_for('portfolio.info') }}#accessibility">Accessibility</a></li>
				{% for link in content.footer_links %}
				<li class="footer__list-item"><a class="footer__link" href="{{ link.url }}">{{ link.label }}</a></li>
				{% endfor %}
			</ul>
		</nav>
	</div>
</footer>

personal_website/templates/modules/header.html
<header class="header">
	<div class="container">
		<a href="/">
			<h1 class="header__title">{{ page_info.title }}</h1>
		</a>
		<h2 class="header__tagline">{% if not tagline %}{{ page_info.tagline }}{% else %}{{ tagline }}{% endif %}</h2>
	</div>
</header>

personal_website/templates/modules/mascot.html
{% if mascot %}
<br>
<pre class="mascot" aria-label="My cute rabbit mascot saying '{{ text }}'">{{ mascot | replace("??", text) }}</pre>
{% endif %}

personal_website/templates/modules/meta.html
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="og:title" content="{{ page_info.title }}" />
<meta name="description" content="{{ page_info.description }}" />
<meta name="og:description" content="{{ page_info.description }}" />
<title>{% block title %}{{ page_info.title }} - {{ page_info.tagline }}{% endblock %}</title>

personal_website/templates/modules/section.html
<section class="section" {% if id %}id="{{ id }}" {% endif %}>
	{% if title %}
	<h2 class="section__headline">{{ title }}</h2>
	{% endif %}
	{% if text %}
	<p class="section__text">{{ text | urlize(50, true) }}</p>
	{% endif %}
	<nav aria-label="{{ links_aria }}">
		{% for link in links %}
		<a class="button" href="{{ link.url }}">{{ link.label }}</a>
		{% endfor %}
	</nav>
</section>

personal_website/templates/portfolio/homepage.html
{% extends "./base.html" %}
{% block content %}
{% include 'modules/featured_projects.html' %}
{% include 'modules/about.html' %}
{% endblock %}

personal_website/templates/portfolio/info.html
{% extends "./base.html" %}
{% block title %}{{ content.pages.portfolio.title }} - {{ content.pages.portfolio.tagline }}{% endblock %}
{% block content %}
{% with id='privacy', title='Privacy', text=privacy_text, links=content.pages.info.links %}
{% include 'modules/section.html' %}
{% endwith %}
{% with id='accessibility', title='Accessibility', text=accessibility_text, links=content.pages.info.links %}
{% include 'modules/section.html' %}
{% endwith %}
{% endblock %}